# Generated by Django 5.0.6 on 2024-05-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0004_alter_kategori_nama_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailResepMasakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('bahan', models.TextField()),
                ('cara_buat', models.TextField(blank=True)),
                ('gambar', models.ImageField(blank=True, default=None, null=True, upload_to='gambar/resep_masakan')),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jenis_detail_resep_masakan', to='rm_app.jenis')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kategori_detail_resep_masakan', to='rm_app.kategori')),
            ],
        ),
    ]
