# Generated by Django 5.0.6 on 2024-05-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0007_menuutama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuutama',
            old_name='deskripsi',
            new_name='informasi',
        ),
        migrations.RenameField(
            model_name='menuutama',
            old_name='resep_masakans',
            new_name='rekomendasi',
        ),
    ]
