# Generated by Django 5.0.4 on 2024-05-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0008_rename_deskripsi_menuutama_informasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailresepmasakan',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status_detail_rese', to='rm_app.statusmodel'),
        ),
    ]
