# Generated by Django 5.0.6 on 2024-05-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0009_detailresepmasakan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailresepmasakan',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status_detail_resep', to='rm_app.statusmodel'),
        ),
    ]
