# Generated by Django 5.0.6 on 2024-05-15 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0010_alter_detailresepmasakan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailresepmasakan',
            name='user_create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_detail_resep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailresepmasakan',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_detail_resep', to=settings.AUTH_USER_MODEL),
        ),
    ]
